### ISSUE TITLE
How to extract birth year?

### ISSUE THREAD

**Issue by crocodilered** [nextgis/memorial_data#2]
In the persons page I  see  birthdate field but it has stange values (59904 for example) and it is not a link to another page af far as I can see. So the question is "How to extract birth year?".

**Comment by simgislab** [comment]
can you provide a link to a specific dataset/file, there are multiple sources here

**Comment by crocodilered** [comment]
In this zip: https://github.com/nextgis/memorial_data/tree/master/data/lists.memo.ru-disk you have file persons.csv. Htis file has BIRTHDATE column with values: 59904, 57856, 50176....

**Comment by crocodilered** [comment]
Maxim, I've go the answer from another developer so thank you!

**Comment by definiteIymaybe** [comment]
@crocodilered if you got the answer, could you describe it here, please?

**Comment by crocodilered** [comment]
Sure, pal. The date fields are encoded with bits mask so you can extract data with theese operations (PHP code, $src is database field value):

 $day = $src & 31;
 $month = ($src >> 5) & 15;
 $year = ($src >> 9) & 255;

remember, date can be full (12.10.1904), month only: (10.1904) or year only (1904) so after thar operations you have to check calculated values:
 if( $year > 0 ) ...

**Comment by brainstorm1313** [comment]
This information should be placed in the readme.
It was very difficult for me to get this information. Nobody can guess to look for it in a closed issue.
By the way, 1800 should be added to the year.

**Comment by simgislab** [comment]
no problem, 1. place it, 2. send a pull-request, 3. We'll merge

it's opensource
